### ISSUE TITLE
allow passing options to the returned function?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/is-match#6]
This will make it a bit more dynamic. Something like

``` js
var matcher = require('is-match')
var isMatch = matcher('foo*', {})

isMatch('foobar', { ignore: '*bar' }) // false
```

**Comment by tunnckoCore** [comment]
@jonschlinkert ping pong. I'm just checking my opened prs and issues.

**Comment by jonschlinkert** [comment]
closing, since this defeats the purpose of returning a matcher function
